### PR TITLE
Changing function names to camelCase, e.g. `sendPOST` => `sendPost`

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Closes https://github.com/Codeception/module-rest/issues/20

### CODE REVIEW

**Comment by SamMousa** [comment]
Please do a global search for the changed terms. At least documentation.md contains old references.

**Comment by ThomasLandauer** [comment]
> Please do a global search for the changed terms. At least documentation.md contains old references.

I hope I got 'em all :-)  
https://github.com/Codeception/module-rest/blob/master/documentation.md is generated automatically, isn't it?

**Comment by SamMousa** [comment]
I'm not sure tbh.

**Review by SamMousa — APPROVED** [review]

**Comment by ThomasLandauer** [comment]
As far as I know, documentation is created when a new release is made.

**Pull request merged**
