### PR TITLE
Update REST.php

### PR DESCRIPTION
**Pull request by ThomasLandauer**
See https://github.com/Codeception/module-rest/issues/22

### CODE REVIEW

**Comment by TavoNiievez** [comment]
@ThomasLandauer Could you please fix the conflicts in this PR?
Sorry, it's a pretty old one.

**Comment by ThomasLandauer** [comment]
OK, done - but I don't know what this is all about ;-)

**Comment by W0rma** [comment]
@ThomasLandauer Your latest commits broke the CI because now the method `deleteHeader()` exists twice in `Rest.php`.

Are you familiar with `git rebase`? I guess that's the right tool to fix the conflicts with the `master` branch.

I just cherry-picked your first commit, rebased and created the PR https://github.com/Codeception/module-rest/pull/106

**Comment by ThomasLandauer** [comment]
> Are you familiar with `git rebase`?

No :-( I'm using GitHub's website...

> I just cherry-picked your first commit, rebased and created the PR #106

Sure! So I can close here?

**Comment by W0rma** [comment]
> So I can close here?

Yes, I think so.

**Pull request closed without merging**
