### PR TITLE
Update JsonArray.php

### PR DESCRIPTION
**Pull request by SoftCreatR**
Resolves https://github.com/Codeception/module-rest/issues/24#issuecomment-721051570

### CODE REVIEW

**Review by alexk984 — APPROVED** [review]

**Comment by mwi-gofore** [comment]
This should fix #38

**Comment by mwi-gofore** [comment]
> This should fix #38

Can confirm that this PR fixes this issue in our test suite. Still trying to figure out the rest of the problems ;)

**Comment by SoftCreatR** [comment]
There are no other issues.

**Comment by Naktibalda** [comment]
Released as 1.2.7

**Pull request merged**
