### PR TITLE
Update to min php8

### LINKED ISSUE #69: [PHP8.1] Upgrade to JSONPath 0.8 to fix deprecated warnings
Would be nice to upgrade to JSONPath 0.8.0 to be able to fully use this with PHP 8.1 without any deprecated warnings:
https://github.com/SoftCreatR/JSONPath/releases/tag/0.8.0

> Note: With this version PHP 7 is not supported anymore.

### PR DESCRIPTION
**Pull request by pbojan**
- Update softcreatr/jsonpath

### CODE REVIEW

**Comment by pbojan** [comment]
@TavoNiievez thanks for looking into the PR, any plans to release a new version?

**Comment by medliii** [comment]
@TavoNiievez  Could you add new tag for current master? 🙏

**Comment by TavoNiievez** [comment]
It was already released as version [3.0.x ](https://github.com/Codeception/module-rest/releases/tag/3.0.0)

**Comment by TavoNiievez** [comment]
@medliii It was already released as version [3.0.x ](https://github.com/Codeception/module-rest/releases/tag/3.0.0)

**Comment by TavoNiievez** [comment]
It was already released as version https://github.com/Codeception/module-rest/releases/tag/3.0.0

**Comment by TavoNiievez** [comment]
@medliii https://github.com/Codeception/module-rest/releases/tag/3.0.0

**Comment by TavoNiievez** [comment]
@medliii It was already released as version https://github.com/Codeception/module-rest/releases/tag/3.0.0

**Pull request merged**
