### PR TITLE
replace flow/jsonpath with softcreatr/jsonpath

### PR DESCRIPTION
**Pull request by TavoNiievez**
flow/jsonpath project is now marked as abandoned and suggests using softcreatr/jsonpath as a replacement.

### CODE REVIEW

**Comment by SamMousa** [comment]
Do not merge this; it depends on an unreleased version of the library.
Instead we should wait until a 1.0 of the library is released that does support older PHP versions; or alternatively wait until we drop support for older PHP versions.

**Comment by TavoNiievez** [comment]
@SamMousa Can you specify which is the 'unreleased version' you mean?

**Comment by SamMousa** [comment]
Your constraint for the library is this: `dev-php-56 | ^0.6`.

These are both non-stable releases according to semver.

**Comment by TavoNiievez** [comment]
imagen

@SamMousa marked as draft while support for php 7.0 and 7.1 is released.

**Comment by TavoNiievez** [comment]
@SamMousa Done.
Please note that the prefix 'dev' does not mean 'unstable' [the new repository](https://github.com/SoftCreatR/JSONPath#installation). Its true meaning is 'legacy'. And regarding waiting for a version 1.0 it is not necessary either. [The old repository](https://github.com/FlowCommunications/JSONPath/tags) was always in versions 0.x and that does not mean that it was 'always unstable'.

**Pull request closed without merging**
