### PR TITLE
Xpath compatibility

### PR DESCRIPTION
**Pull request by pamoller**
Transforming JSON documents to XML document to use with XPath causes a loss of information, cause the `string` operator translates `true` and `null` to `''`

````php
 $subNode->nodeValue = htmlspecialchars((string)$value);
````

So boolean values can't be found by an expression like:

````php
$I->seeResponseJsonXpathEvaluatesTo("//boolean[text() = 'true']");
`````

Using a more elaborated transformation, https://tqdev.com/2017-converting-json-to-xml-in-javascript-and-php, keeps all informations:

````json
{"boolean":true, "number": -1.2780E+2, "null": null, "string": "i'am a sentence"}
````  

transforms to now

````xml
<root>
   <boolean type="boolean">true</boolean>
   <number type ="number">-127.8</number>
   <null type="null"></null>
   <string type="string">i'am a sentence</string>
</root>
````

so see now: JsonArrayTest.php

### CODE REVIEW

**Comment by Naktibalda** [comment]
Please rebase your branch on master branch of this repository.

**Comment by Naktibalda** [comment]
It seems that you forgot to fetch

**Comment by pamoller** [comment]
So everything ok, wright now?

**Comment by Naktibalda** [comment]
16 commits is not ok, it shows commits from your previous pull request.
It would probably be better start a new branch based on master (or `git reset --hard`)  and cherry-pick commits from this branch,

**Comment by pamoller** [comment]
I created an new pull request, hopes that fit the needs :)

**Pull request closed without merging**
