### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by ThomasLandauer**
Removing `flow/jsonpath` dependency, see https://github.com/Codeception/module-rest/issues/24#issuecomment-714807087

Closes https://github.com/Codeception/module-rest/issues/24

### CODE REVIEW

**Comment by SoftCreatR** [comment]
This would break the lib, since JSONPath is used here: https://github.com/Codeception/module-rest/blob/master/src/Codeception/Util/JsonArray.php

A better solution has been provided: https://github.com/Codeception/module-rest/issues/24#issuecomment-720465715

**Comment by ThomasLandauer** [comment]
See https://github.com/Codeception/module-rest/pull/31 for the current plan: Remove it as a dependency, and explain users how to install it by themselves.

**Comment by SoftCreatR** [comment]
> See #31 for the current plan: Remove it as a dependency, and explain users how to install it by themselves.

That doesn't change the fact, that your PR would break the lib ;)

**Comment by TavoNiievez** [comment]
@ThomasLandauer what **SoftCreatR** is trying to say is that if the goal was to remove the library, you would have to remove this functions as well:
https://github.com/Codeception/module-rest/blob/15e16e4a9973ffaeffc39208787e60e5d8316788/src/Codeception/Module/REST.php#L1056-L1252
https://github.com/Codeception/module-rest/blob/15e16e4a9973ffaeffc39208787e60e5d8316788/src/Codeception/Util/JsonArray.php#L85-L91
So as not to break the installation and the **tests** themselves.

However, it is better to wait for the owners to decide whether [the changes](https://github.com/SoftCreatR/JSONPath/issues/28) made by **SoftCreatR** to make the semantic versioning less confusing are enough to keep that code unchanged.

**Comment by Naktibalda** [comment]
Replaced by #35

**Pull request closed without merging**
